baseURL: "https://mogita.com/"
languageCode: "en-US"
defaultContentLanguage: "en"
title: "mogita"
theme: "hugo-coder"

enableInlineShortcodes: true
disqusShortname: otaku-mogita
enableGitInfo: true
assetDir: "static"

pygmentsStyle: "nord"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

paginate: 100
permalinks:
  posts: "/:slug"
#  /about: "/about.html"
uglyURLs: true

# --- ezhil compatible params ---
# copyright: "Copyright ¬© 2010-{year} mogita"
# paginatePath: "page"
#
# params:
# subtitle: "Ê∫ÄÈñã„ÅÆËä±„Åå‰ººÂêà„ÅÑ„ÅÆ„Ç´„Çø„Çπ„Éà„É≠„Éï„Ç£„Éº"
# customCSS: "css/ezhil-custom.css"
# customDarkCSS: "css/ezhil-custom.css"
# mode: dark
# categories:
#   tech: üõ†Ô∏è
#   journal: üìñ
#   music: üé∏
# social:
#   - name: "Twitter"
#     icon: "twitter"
#     url: "https://twitter.com/mogita"
#   - name: "GitLab"
#     icon: "gitlab"
#     url: "https://gitlab.com/mogita"
#   - name: "LinkedIn"
#     icon: "linkedin"
#     url: "https://linkedin.com/in/yun-wang-646d753d/"

# --- hugo coder compatible params ---
params:
  # author: "mogita"
  info: "an empty stack developer seeing the world through code"
  description: "mogita's personal website"
  keywords: "blog,developer,personal"
  gravatar: "me@mogita.com"
  since: 2010
  colorScheme: "auto"
  highlight: true
  favicon_16: "img/favicons/favicon16.png"
  favicon_32: "img/favicons/favicon32.png"
  touchIcon: "img/favicons/favicon.png"
  # customCSS: ["css/custom.css"]
  # customSCSS: ["scss/custom.scss"]
  # customJS: ["js/custom.js"]
  social:
    - name: "GitHub"
      icon: "fa fa-github fa-2x"
      url: "https://github.com/mogita"
    - name: "Fediverse"
      icon: "fa fa-brands fa-mastodon fa-2x"
      url: "https://mog.blue/@mogita"
    # - name: "GitLab"
    #   icon: "fa fa-gitlab fa-2x"
    #   url: "https://gitlab.com/mogita"
    # - name: "LinkedIn"
    #   icon: "fa fa-linkedin fa-2x"
    #   url: "https://linkedin.com/in/yun-wang-646d753d/"

menu:
  main:
    - identifier: "blog"
      name: "Blog"
      title: "Blog"
      url: "/posts.html"
      weight: 1
    - identifier: "rss"
      name: "RSS"
      title: "RSS"
      url: "/index.xml"
      weight: 10
    - identifier: "tags"
      name: "Tags"
      title: "Tags"
      url: "/tags.html"
      weight: 15
    - identifier: "about"
      name: "About"
      title: "About"
      url: "/about.html"
      weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
