baseURL: "https://blog.mogita.com/"
languageCode: "en-us"
title: "mogita"
copyright: "Copyright Â© 2010-{year} mogita"
theme: "ezhil"
enableInlineShortcodes: true
disqusShortname: otaku-mogita
enableGitInfo: true
assetDir: "static"

pygmentsStyle: "nord"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

summaryLength: 0
paginate: 100
paginatePath: "page"
permalinks:
  /about: "/about.html"
  posts: "/:slug"
uglyURLs: true

params:
  subtitle: "æº€é–‹ã®èŠ±ãŒä¼¼åˆã„ã®ã‚«ã‚¿ã‚¹ãƒˆãƒ­ãƒ•ã‚£ãƒ¼"
  highlight: true
  customCSS: "css/ezhil-custom.css"
  customDarkCSS: "css/ezhil-custom.css"
  mode: dark
  categories:
    tech: ğŸ› ï¸
    journal: ğŸ“–
    music: ğŸ¸
  social:
    - name: "Twitter"
      icon: "twitter"
      url: "https://twitter.com/mogita"
    - name: "GitLab"
      icon: "gitlab"
      url: "https://gitlab.com/mogita"
    - name: "LinkedIn"
      icon: "linkedin"
      url: "https://linkedin.com/in/mogita"

menu:
  main:
    - identifier: "home"
      name: "Home"
      title: "Home"
      url: "/"
      weight: 1
    - identifier: "rss"
      name: "RSS"
      title: "RSS"
      url: "/index.xml"
      weight: 10
    - identifier: "tags"
      name: "Tags"
      title: "Tags"
      url: "/tags.html"
      weight: 15
    - identifier: "about"
      name: "About"
      title: "About"
      url: "/about.html"
      weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true

